# Generated by Django 6.1 on 2026-08-30 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionoverride',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.permission'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorization.role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('user', 'tenant', 'permission'), name='unique_tenant_wide_permission_override'),
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('user', 'tenant', 'campus', 'permission'), name='unique_campus_scoped_permission_override'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('user', 'tenant', 'role'), name='unique_tenant_wide_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('user', 'tenant', 'campus', 'role'), name='unique_campus_scoped_role_assignment'),
        ),
    ]
