# Generated by Django 6.1 on 2026-09-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_created_by_tenant_updated_by'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproviderevent',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text="Null if the webhook reference didn't match any known Payment.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
    ]
